### ISSUE TITLE
New feature files are not supporting as expected

### ISSUE THREAD

**Issue by rakeshnambiar** [alapanme/Cypress-Automation#2]
Hi @alapanme many thanks for sharing the template and appreciate your efforts.

I just tried with a new feature file and it always says `Step implementation missing`. When I copy the scenario to your `login.feature` file it's working. I have also tried to rename the existing `login.feature` to some invalid name like `xlogin.featurex` and create a copy of the same file like `login-new.feature` and still getting the same error. Is this configured somewhere apart from the below mentioned settings on Cypress.json file? Please could you help?
```
  "testFiles": [
    "**/*.{feature,features}"
  ],
```

```
  1) Login
       Login to Orange CRM Website (example #1):
     Error: Step implementation missing for: User is at the login page
```

**Comment by alapanme** [comment]
Hey @rakeshnambiar Can you add the following details:

- Screenshot of Project structure (make sure it shows where is your feature files and step definition files are)
- Your cypress.json file
- Your package.json file

**Comment by rakeshnambiar** [comment]
@alapanme thanks for your reply. Here's the details.

![image](https://user-images.githubusercontent.com/20258636/144878307-7a9468b4-537b-4d41-90aa-0a1cb138c847.png)

`cupress.json` 

```
{
  "watchForFileChanges": false,
  "chromeWebSecurity": false,
  "testFiles": [
    "**/*.{feature,features}"
  ],
  "retries": 1,
  "reporter": "../node_modules/mochawesome/src/mochawesome.js",
  "reporterOptions": {
    "overwrite": false,
    "html": false,
    "json": true
  },
  "baseUrl": "https://opensource-demo.orangehrmlive.com/",
  "projectId": "d5zibb",
  "experimentalStudio": true,
  "env": {
    "db": {
      "host": "db4free.net",
      "user": "username",
      "password": "password",
      "database": "db_name"
    }
  }
}
```

`package.json`

```
{
  "name": "cypress-automation",
  "version": "1.0.0",
  "description": "Cypress Automation by Testersdock",
  "main": "index.js",
  "scripts": {
    "test": "cypress open",
    "delete:reportFolder": "rm -rf mochawesome-report/",
    "test:cli": "npm run delete:reportFolder && cypress run",
    "merge:reports": "mochawesome-merge mochawesome-report/*.json > cypress-combined-report.json",
    "create:html:report": "npm run merge:reports && marge --reportDir TestReport cypress-combined-report.json"
  },
  "author": "Alapan",
  "license": "ISC",
  "devDependencies": {
    "@4tw/cypress-drag-drop": "^1.8.0",
    "cypress": "^9.1.1",
    "cypress-cucumber-preprocessor": "^4.2.0",
    "cypress-downloadfile": "^1.2.0",
    "cypress-file-upload": "^5.0.8",
    "cypress-real-events": "^1.5.1",
    "cypress-recurse": "^1.8.1",
    "cypress-select-tests": "^1.7.1",
    "mocha": "^8.3.2",
    "mochawesome": "^6.2.2",
    "mochawesome-merge": "^4.2.0",
    "mochawesome-report-generator": "^5.2.0",
    "mysql": "^2.18.1"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
}
```

**Comment by alapanme** [comment]
You can make the following changes in your `package.json` file. Keep the **nonGlobalStepDefinitions** as `false` and then give the relative path under **stepDefinitions**. If the relative path doesn't work, try with the absolute path. Also, make sure that the feature file and step definition files have the same name, otherwise it won't work.

```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "cypress/integration/cucumber-test/l"
  }
```

**Comment by rakeshnambiar** [comment]
Many thanks. It worked !!!
Btw - Have you noticed any sort of slowness in the execution time after adding the tag filter or the number of feature files and scenarios are growing when compares to the normaly Cypress execution? 
Also, have you tried to incorporate the Cucumber-BDD report same as `SerenityJS`. Please let me know your thoughts.
