### ISSUE TITLE
Drag and drop with angular material cdk won't work with angular13

### ISSUE THREAD

**Issue by tricodon** [alapanme/Cypress-Automation#4]
We are currently not able to get 

https://github.com/alapanme/Cypress-Automation/blob/c92d7536e2a21c713d72b28ada9ba1d2a624921e/cypress/integration/TC_23_dragAndDrop.spec.js#L29

work with a13, but it is still working with a12 when changing the url to v12: `cy.visit('https://v12.material.angular.io/cdk/drag-drop/overview#cdk-drag-drop-connected-sorting')`.

Maybe there are any suggestions...

(Thanks for this cool repo btw)

**Comment by tricodon** [comment]
It can be fixed by setting the main mouse button when triggering mousedown:

`draggable.dispatchEvent(new MouseEvent('mousedown', { buttons: 1 }));`

**Comment by alapanme** [comment]
Hey, glad you were able to solve the issue.
